name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.HUB_USER_NAME }}
          password: ${{ secrets.HUB_PASSWORD }}
      - name: Build and push
        run: |
          docker build -t ${{ secrets.HUB_USER_NAME }}/app:latest .
          docker push ${{ secrets.HUB_USER_NAME }}/nodeapp:latest

      
