name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name:  Build the Docker image & Push to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
       image: nadaessam1806/napp
       registry: docker.io
       dockerfile: Dockerfile
       username: ${{ secrets.HUB_USER_NAME }}
       password: ${{ secrets.HUB_PASSWORD }}
       tags: latest

      
